name: Ansible folder

on:
  push:
    paths:
      - 'ansible/**'

jobs:
  handle-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Echo change
        run: echo "ansible folder changed!"

        
